### ISSUE TITLE
Disciplinas 

### ISSUE THREAD

**Issue by eneiasraul** [ADSCajazeiras/paginadocurso#3]
## Disciplinas e Corpo Docente

* Descrição de disciplinas e corpo docente do campus de Cajazeiras

**Comment by edybit** [comment]
Todas as disciplinas com seus respectivos docentes foram descritas  e separadas por semestres.

![Captura da Web_1-7-2023_125656_](https://github.com/ADSCajazeiras/paginadocurso/assets/109600197/ebf08ee6-2334-4018-aee4-7f695f709417)
